packages:
  - 'packages/**/*'
  - 'packages/astro/test/units/_temp-fixtures'
  - 'examples/**/*'
  - 'smoke/**/*'
  - 'scripts'
  - 'benchmark'
  - 'benchmark/packages/*'
  # Below excludes are only for Turbo because it doesn't respect gitignore like pnpm does
  - '!packages/astro/test/units/_temp-fixtures/*'
  - '!**/.vercel/**'

catalog: 
  tinyglobby: ^0.2.12
  tinyexec: ^0.3.2
  shiki: ^1.29.2
  preferred-pm: ^4.1.1
  tsconfck: ^3.1.4
  p-limit: ^6.2.0
  zod: ^3.24.1
  vite: ^6.0.11
  rehype-raw: ^7.0.0
